# 首页显示的标题
title:               Matt Reach
tagline:             'An iOS Developer'

# github 用户名
github_username:     debugly

# atom url
url:                 http://debugly.cn

# 每页多少篇博客
paginate:            6

# 作者
author:
  name:              许乾隆
  email:             qianlongxu@gmail.com

# 侧边导航栏头部
sidebar-nav-header:  '<p>滚滚东逝水，淘尽英雄泪。</p><p>青山依旧在，几度夕阳红。 </p><p>古今多少事，都付笑谈中。</p>'

# 侧边导航栏条目
sidebar-nav-items:   [{'target':'/','value':'首页'},{'target':'/categories/','value':'分类'},{'target':'/about/','value':'关于'}]

# 版本
version:             0.0.2
